### ISSUE TITLE
Upgrade to newer gradle and IDEA

### ISSUE THREAD

**Issue by barspi** [rholder/gradle-view#11]
Currently the project is bases on an outdated Gradle 1.12
It would be convenient to upgrade to a newer gradle version (2.3+ preferable), together with making certain it also works with the latest (14.x+) Intellij IDEA versions.
(Ideally, it could use the current project's Gradle settings, but I'm not sure it's doable)

One thing that failed me with the current gradle-view version is this new Gradle syntax for plugins, which makes Gradle 1.12 break:

```
plugins {
    id "fi.jasoft.plugin.vaadin" version "0.9.6"
}
```

**Comment by rholder** [comment]
The [2.1.0 release](https://github.com/rholder/gradle-view/releases/tag/v2.1.0) should now be using the Gradle 2.3 tooling API. What this means is that the Gradle plugin itself should be able to handle many more Gradle versions than the previous 1.12 tooling API (but also maintain backward compatibility). It will always use the project's preferred Gradle (as set by the target project's Gradle wrapper) when running Gradle. Feel free to pull the latest `.zip` from that tagged release here on GitHub as it will likely be a few days before JetBrains approves the same file on their plugin repository. Let me know if you have any more issues with this release.
